### ISSUE TITLE
[Possible bug] `transform()` raises when number of batches is less than what `fit()` was called with

### ISSUE THREAD

**Issue by H2CO3** [CoAxLab/pycombat#5]
Hi there,

I am not sure if this is a bug, because I'm not familiar enough with the maths behind ComBat. In any case, I have a feeling this should work, so here it is.

I have a training pipeline in which random sampling occasionally results in a hold-out test set that does not represent all batches. When calling `combat.transform(X_test)` on the already-fit `Combat` instance, I get the following exception:

```python
ValueError: Wrong number of categories for b
```

Obviously, if there were an _additional_, new batch at `transform()` time that was unknown at `fit()`ting time, that would be a legitimate error, because no state could have been recorded as to how that unknown batch must be corrected. However, I think asking for a transform that doesn't include all the batches previously encountered shouldn't be considered an error.

Accordingly, I propose the following change to `pycombat.py`:

```diff
< if len(np.unique(b)) != self.gamma_.shape[0]:
> if len(np.unique(b)) > self.gamma_.shape[0]:
```

Would this be possible, or is it a fundamental necessity of the ComBat algorithm that the number of batches be exactly the same when fitting and transforming? If it is something fundamental that cannot be fixed, then how do people deal with this kind of problem?

**Comment by jrasero** [comment]
Hi @H2CO3 !!!

First of, apologies for so so so delayed response!! I don't know why I didn't get a notification about this :/

Thanks a lot for reporting this!!! Yeah, you are right. In principle, an error shouldn't be raised even if your new data don't contain all the batches used to fit the Combat model. 

All you need is that the batch labels for the new test set were part of the batches that you used to fit the ComBat model (e.g. center o study id).

Thus, instead of your proposed suggestion, I would check that the batch labels in the test set,i.e., `np.unique(b)` , https://github.com/CoAxLab/pycombat/blob/f19671974a93c1918f42a8c4c113106811547287/pycombat/pycombat.py#L262 they are all contained in the batches used to fit the model, i.e.,   `self.batches_ ` https://github.com/CoAxLab/pycombat/blob/f19671974a93c1918f42a8c4c113106811547287/pycombat/pycombat.py#L136.

Would you be willing to contribute to this? :-)

**Comment by H2CO3** [comment]
Hey, thanks for getting back to this! Sure, I'll try to write up a quick PR for this soon.

**Comment by H2CO3** [comment]
@jrasero I think I've got a fix.

**Comment by H2CO3** [comment]
@jrasero any updates on this?

**Comment by jrasero** [comment]
Hi Árpád,

I haven't had a chance to look into this. I'll do it this weekend.

Thanks a lot for the pull-request, anyway!

Cheers,
Javi

**Comment by H2CO3** [comment]
@jrasero Did you have a chance to look at my PR?

**Comment by H2CO3** [comment]
@jrasero is this project dead? Should I fork it instead of waiting for the PR to be merged?

**Comment by jrasero** [comment]
Hi @H2CO3 . No, no, this is not dead, but I completely forgot to get my hands on your PR. Many things going on these months. I hope I can do it very soon.

In any case, you are always free to fork the repo and make as many changes as you want in your space. I've got no problems with that.
